#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/pillow
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#  OAuth2:
#    google:
#      #      url: https://accounts.google.com/o/oauth2/v2/auth
#      client-id: 422145577673-9pi0ubc9n5k1soetj6bn9uh4l0d76hm9.apps.googleusercontent.com
#      client-secret: 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
#    #      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
#    #      BaseURL : https://oauth2.googleapis.com/token
#    kakao:
#      client-id: e3d99f51062af853c8299e9ca1edeeef
#      client-secret: CjT0wwM0U3UinpIY9NUqHU4froBfEVLr
#
#    apple:
#      client-id: clonect.com.feeltalk
#      auth-url: https://appleid.apple.com
#      key-id: XDVLLW9Q3T
#      team-id: K5RZZ64DS3
#      redirect-url: https://clonect.net/login/apple
#      key-path: AuthKey_XDVLLW9Q3T.p8
#    #      key-path : /home/ec2-user/server_jars/AuthKey_XDVLLW9Q3T.p8
#
#
#
#fcm:
#  key: "key= AAAAYknWUsk:APA91bGbnNM0UoHF04F69nbIvTd2LSvZN3H0dvm3fNRxbKPN2QBK6pkmQdWmjbZun7ctAIyeaxcsGZJu0ECtyGpRkPao3vmnEYU_jFz3HA7squf0BdLo84skWjDfMgahTuJ0RTeMcCko"
#  url: "https://fcm.googleapis.com/fcm/send"
#
#cloud:
#  aws:
#    s3:
#      bucket: pillow.images
#    credentials:
#      access-key: AKIATNQGZT5PT7UTX2NR
#      secret-key: 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
#    region:
#      static: ap-northeast-2
#      auto: false
#    stack:
#      auto: false
#
#logging:
#  level:
#    com:
#      amazonaws:
#        util:
#          EC2MetadataUtils: ERROR
